defmodule Draught.CLI.Task.Stream.Indicator.Captions do
  @moduledoc """
  Provides a fixed cycle of short, display-safe activity captions.

  Captions are presentation only, not reports of tool execution or progress.
  The caller shuffles the catalog's index order at the presentation boundary;
  this catalog introduces no randomness or execution effects.
  """

  @captions {
    "Lollygagging…",
    "Consulting the grimoire…",
    "Rolling for insight…",
    "Counting spare lockpicks…",
    "Untangling enchanted cables…",
    "Checking the quest log…",
    "Polishing a spare rune…",
    "Negotiating with a mimic…",
    "Keeping both knees intact…",
    "Refilling the mana pool…",
    "Following the side quest…",
    "Sorting enchanted bookmarks…",
    "Rolling a wisdom check…",
    "Deciphering wizard notes…",
    "Looking for the save point…",
    "Dusting off the spellbook…",
    "Comparing suspicious maps…",
    "Feeding the rubber duck…",
    "Consulting the greybeards…",
    "Untying a wizard knot…",
    "Packing extra torches…",
    "Counting unspent skill points…",
    "Inspecting the suspicious door…",
    "Sharpening a wooden pencil…",
    "Taming a recursive dragon…",
    "Reading the tiny runes…",
    "Asking the tavern keeper…",
    "Checking for secret passages…",
    "Teaching a goblin to type…",
    "Sorting the potion shelf…",
    "Adjusting the wizard hat…",
    "Listening for dungeon echoes…",
    "Looking under the welcome mat…",
    "Bartering for better clues…",
    "Rolling against confusion…",
    "Untangling the loot table…",
    "Keeping the party together…",
    "Consulting an elderly oak…",
    "Counting enchanted acorns…",
    "Bribing the bridge troll…",
    "Aligning the quest markers…",
    "Warming up the forge…",
    "Tracing a wandering rune…",
    "Translating goblin shorthand…",
    "Checking the bottomless bag…",
    "Following a helpful raven…",
    "Finding the missing semicolon…",
    "Sorting soul gems…",
    "Looking for a friendly inn…",
    "Rolling for initiative…",
    "Checking the dragon forecast…",
    "Recharging a stubborn wand…",
    "Reading the dungeon footnotes…",
    "Negotiating with mudcrabs…",
    "Folding a very large map…",
    "Balancing the party inventory…",
    "Untangling elven headphones…",
    "Consulting a mildly wise owl…",
    "Counting the corridor turns…",
    "Refactoring a tiny spell…",
    "Checking for cursed loot…",
    "Rolling a perception check…",
    "Decoding the prophecy margin…",
    "Avoiding suspicious sweetrolls…",
    "Organizing the scroll case…",
    "Asking a passing adventurer…",
    "Looking for the spare key…",
    "Comparing wizard handwriting…",
    "Stirring a harmless potion…",
    "Inspecting the empty chest…",
    "Following the lantern light…",
    "Teaching a familiar to fetch…",
    "Counting the party snacks…",
    "Checking the rune dictionary…",
    "Debugging a spellbook…",
    "Taking the scenic dungeon…",
    "Restocking imaginary arrows…",
    "Listening to the talking door…",
    "Charting the next corridor…",
    "Rolling for arcana…",
    "Borrowing a wizard pencil…",
    "Untangling the chain mail…",
    "Checking the map legend…",
    "Reading a dusty changelog…",
    "Looking for the hidden lever…",
    "Consulting the dice bag…",
    "Negotiating a short rest…",
    "Sorting the enchanted socks…",
    "Counting friendly dragons…",
    "Chasing a runaway bookmark…",
    "Inspecting the quest board…",
    "Looking beyond the fog…",
    "Brewing a cup of patience…",
    "Rolling a history check…",
    "Calibrating the magic compass…",
    "Searching the bard's notes…",
    "Untangling a stack of scrolls…",
    "Checking the familiar's notes…",
    "Consulting the pocket oracle…",
    "Counting septims…",
    "Following the breadcrumb trail…",
    "Stowing the oversized shield…",
    "Rolling for investigation…",
    "Sorting a bag of holding…",
    "Comparing two ancient tablets…",
    "Checking the spell ingredients…",
    "Finding the quiet campfire…",
    "Polishing the crystal ball…",
    "Making room for one more clue…",
    "Dodging arrows and deadlines…",
    "Reading the wizard's README…",
    "Untangling a spectral stack…",
    "Consulting the dungeon index…",
    "Looking for the optional boss…",
    "Counting the glowing mushrooms…",
    "Checking the ranger's compass…",
    "Bartering with a sleepy sphinx…",
    "Rolling against distraction…",
    "Finding a path through runes…",
    "Keeping an eye on the mimic…",
    "Waiting for the drawbridge…",
    "Haggling over a copper piece…",
    "Unpacking the emergency cloak…",
    "Checking a suspicious floor…",
    "Remembering the secret knock…",
    "Peeking behind the tapestry…",
    "Taking notes in dwarvish…",
    "Rehearsing a dramatic entrance…",
    "Leaving room for dessert loot…",
    "Finding a troll-free route…",
    "Reading the fine parchment…",
    "Unjamming the portcullis…",
    "Counting stairs in the tower…",
    "Making friends with a gargoyle…",
    "Reuniting a pair of gauntlets…",
    "Following the less muddy road…",
    "Preparing a heroic footnote…",
    "Remembering where we parked…",
    "Waiting for the ferry goblin…",
    "Checking the moat depth…",
    "Acknowledging the town crier…",
    "Translating an ancient typo…",
    "Practicing a convincing nod…",
    "Picking the quieter tunnel…",
    "Borrowing a ladder from elves…",
    "Finding the castle back door…",
    "Returning an overdue scroll…",
    "Mapping the oddly square cave…",
    "Checking a knight's references…",
    "Untwisting the grappling rope…",
    "Keeping the torch upright…",
    "Leaving a note for the oracle…",
    "Weighing the suspicious crown…",
    "Assembling the travel rations…",
    "Measuring a very small moat…",
    "Listening at the wrong door…",
    "Locating the inn's lost key…",
    "Taking the stairs this time…",
    "Finding a less haunted bench…",
    "Waiting for a prophecy update…",
    "Flipping the hourglass…",
    "Herding a few spectral cats…",
    "Waking the sleeping sentinel…",
    "Comparing dragon silhouettes…",
    "Keeping the camp kettle warm…",
    "Checking the secret handshake…",
    "Choosing a sensible disguise…",
    "Taking attendance at the guild…",
    "Learning the secret knock…",
    "Keeping the scrolls dry…",
    "Finding a portable camp stool…",
    "Ducking beneath a low arch…",
    "Checking for invisible stairs…",
    "Adding a note to the map…",
    "Respectfully poking the obelisk…",
    "Carrying the ceremonial spoon…",
    "Offering the griffin a snack…",
    "Inspecting a suspicious puddle…",
    "Reconsidering the cursed ring…",
    "Waiting for the lift operator…",
    "Filling out a dragon permit…",
    "Escaping the tutorial cave…",
    "Recalling the tavern's name…",
    "Measuring a wizard's shadow…",
    "Staying clear of glowing doors…",
    "Borrowing the paladin's pen…",
    "Fetching the spare scabbard…",
    "Rebalancing the saddle bags…",
    "Untangling the heraldic flags…",
    "Looking for the smaller giant…",
    "Checking the goblin timetable…",
    "Reading between the ley lines…",
    "Finding the watchtower stairs…",
    "Asking which way is north…",
    "Waiting for the talking tree…",
    "Inspecting the borrowed horse…",
    "Preparing a modest flourish…",
    "Filing a quest expense report…",
    "Tracing the labyrinth's edge…",
    "Keeping the decoy dragon fed…",
    "Reciting the safer incantation…",
    "Chalking a protective circle…",
    "Testing an imaginary wand…",
    "Recounting the ritual candles…",
    "Revising a spell's footnotes…",
    "Checking the summoning address…",
    "Untying a temporal shoelace…",
    "Looking up a counterspell…",
    "Finding the less volatile jar…",
    "Adjusting the scrying angle…",
    "Asking the crystal politely…",
    "Measuring a pinch of stardust…",
    "Distinguishing frogs from toads…",
    "Winding the enchanted clock…",
    "Practicing indoor lightning…",
    "Reading a spell upside down…",
    "Calming the animated teapot…",
    "Waiting for the cauldron lid…",
    "Checking the ward's warranty…",
    "Rehearsing a minor illusion…",
    "Unfolding a pocket dimension…",
    "Labeling the harmless jars…",
    "Consulting the wand manual…",
    "Restoring a misplaced aura…",
    "Fitting a cork to the potion…",
    "Teaching a broom to park…",
    "Untangling a teleport circle…",
    "Finding the missing moonstone…",
    "Checking the spell's spelling…",
    "Choosing the quieter thunder…",
    "Negotiating with living ink…",
    "Waving the wand responsibly…",
    "Looking for the ritual spoon…",
    "Recharging a tiny constellation…",
    "Keeping the frost off the tome…",
    "Reducing the goblin sparkle…",
    "Measuring the portal clearance…",
    "Teaching a candle to behave…",
    "Waiting for the familiar…",
    "Unhexing a desk ornament…",
    "Checking the eclipse calendar…",
    "Finding the potion antidote…",
    "Folding a paper phoenix…",
    "Untangling a levitation charm…",
    "Consulting a reluctant mirror…",
    "Rewinding the enchanted spool…",
    "Making peace with the incense…",
    "Sorting real gems from candy…",
    "Checking the wizard's pockets…",
    "Dealing with a floating comma…",
    "Giving the golem directions…",
    "Tuning a pocket thundercloud…",
    "Turning down the rune glow…",
    "Stirring counterclockwise…",
    "Finding the clean mortar…",
    "Writing in invisible pencil…",
    "Checking the portal destination…",
    "Revisiting the spell diagram…",
    "Inspecting a bottle of echoes…",
    "Refilling the ink of mystery…",
    "Keeping the spell within scope…",
    "Threading a silver needle…",
    "Recalling the broom's name…",
    "Finding an unenchanted mug…",
    "Rehearsing the gentle version…",
    "Inviting the ghost to tea…",
    "Calibrating a tiny sundial…",
    "Rebinding the wandering pages…",
    "Waiting for the runes to settle…",
    "Checking the moon's paperwork…",
    "Rolling the less cursed die…",
    "Counting the bonus modifiers…",
    "Remembering the house rules…",
    "Looking up a saving throw…",
    "Shuffling the encounter deck…",
    "Giving the dice a stern look…",
    "Rereading the character sheet…",
    "Finding the missing d12…",
    "Checking the marching order…",
    "Agreeing on who carries loot…",
    "Drawing a slightly better map…",
    "Negotiating with the GM…",
    "Calculating tavern expenses…",
    "Remembering the bard's plan…",
    "Choosing a sensible feat…",
    "Checking the encumbrance limit…",
    "Restoring the snack initiative…",
    "Looking for a spare miniature…",
    "Consulting the encounter notes…",
    "Reconsidering a charisma dump…",
    "Preparing an unlikely backstory…",
    "Making room at the gaming table…",
    "Checking the critical table…",
    "Rolling with mild optimism…",
    "Folding the dungeon screen…",
    "Locating the party's healer…",
    "Reading the ability fine print…",
    "Sharpening the stat pencil…",
    "Counting temporary hit points…",
    "Placing the tiny trees…",
    "Checking whether that stacks…",
    "Remembering the bonus action…",
    "Practicing the merchant voice…",
    "Giving the rogue a minute…",
    "Sorting the inspiration tokens…",
    "Planning a very short detour…",
    "Checking who brought rope…",
    "Finding the rulebook bookmark…",
    "Rolling a remarkably normal die…",
    "Recounting the party's lanterns…",
    "Remembering to bring a cleric…",
    "Checking the rest requirements…",
    "Putting the mimic back on-grid…",
    "Making a note for next session…",
    "Measuring the fireball radius…",
    "Asking if the door is unlocked…",
    "Checking the bard's alibi…",
    "Deciding who talks to the duke…",
    "Keeping the minis upright…",
    "Rereading a suspicious prophecy…",
    "Giving the dice another chance…",
    "Looking up grappling rules…",
    "Choosing an unremarkable alias…",
    "Writing down the NPC's name…",
    "Checking the initiative tracker…",
    "Restocking the pencil supply…",
    "Finding the right spell card…",
    "Counting the extra dice…",
    "Keeping the party on the map…",
    "Remembering the actual quest…",
    "Escorting a stray semicolon…",
    "Untangling a goblin callback…",
    "Giving the daemon a day off…",
    "Teaching a slime to sort…",
    "Chasing a phantom bracket…",
    "Explaining scope to a wizard…",
    "Sorting the goblin backlog…",
    "Checking a rune's return type…",
    "Refactoring the prophecy…",
    "Waiting on an elven coroutine…",
    "Teaching trolls to match…",
    "Finding a dragon-sized cache…",
    "Reopening the spell compiler…",
    "Giving a golem a type hint…",
    "Reading a cursed stack trace…",
    "Keeping the goblins immutable…",
    "Taming a wild off-by-one…",
    "Untangling the wizard's imports…",
    "Consulting the syntax oracle…",
    "Checking the spell's arity…",
    "Explaining tuples to a kobold…",
    "Sorting the enchanted tabs…",
    "Keeping dragons out of scope…",
    "Giving the parser a biscuit…",
    "Revisiting the rune namespace…",
    "Compiling an imaginary potion…",
    "Chasing a nil-shaped shadow…",
    "Checking the goblin changelog…",
    "Returning the borrowed pointer…",
    "Finding the polymorphic frog…",
    "Giving a closure some closure…",
    "Untangling a bardic macro…",
    "Feeding the garbage collector…",
    "Counting invisible whitespace…",
    "Naming the last magic constant…",
    "Keeping the familiar stateless…",
    "Reading the dragon's type spec…",
    "Teaching a rune to tail-call…",
    "Pairing with an imaginary duck…",
    "Finding the phantom dependency…",
    "Checking a wizard's indentation…",
    "Sorting hexes by severity…",
    "Waiting for the potion to link…",
    "Locating the missing base case…",
    "Debugging the crystal's glare…",
    "Explaining recursion to an elf…",
    "Untangling a spectral promise…",
    "Keeping spell effects separate…",
    "Negotiating a dragon mutex…",
    "Inspecting an enchanted diff…",
    "Rebasing a fictional timeline…",
    "Naming a very small function…",
    "Counting the nested spellbooks…",
    "Keeping the goblin API tidy…",
    "Finding a harmless escape hatch…",
    "Tracing a gremlin's footsteps…",
    "Consulting the magical schema…",
    "Teaching a druid to debounce…",
    "Checking the rune's invariants…",
    "Making friends with a linter…",
    "Finding the unmatched brace…",
    "Giving the terminal a cape…",
    "Keeping the daemon housebroken…",
    "Sorting a stack of wizard hats…",
    "Inspecting a phantom warning…",
    "Checking the goblin's checksum…",
    "Untangling a polymorphic scarf…",
    "Choosing a name for the dragon…",
    "Teaching a griffin to memoize…",
    "Drawing a rune boundary…",
    "Explaining ownership to a ghost…",
    "Giving a semaphore a lantern…",
    "Finding the immutable treasure…",
    "Refactoring a goblin recipe…",
    "Consulting a very small enum…",
    "Keeping the elves loosely bound…",
    "Checking the potion's interface…",
    "Tracing the dragon's call graph…",
    "Naming the unnamed familiar…",
    "Waiting for the spell to return…",
    "Following a fox through ferns…",
    "Listening to a patient badger…",
    "Checking the mushroom map…",
    "Offering a squirrel directions…",
    "Finding the dry stepping stone…",
    "Watching the lantern beetles…",
    "Consulting some very old moss…",
    "Counting rings on a fallen tree…",
    "Picking the less prickly path…",
    "Asking the river for a hint…",
    "Following the owl's suggestion…",
    "Negotiating with a tree root…",
    "Finding the moonlit clearing…",
    "Checking the squirrel's stash…",
    "Listening for the forest bell…",
    "Reading a map of the canopy…",
    "Keeping the pinecones in order…",
    "Waiting for the mist to lift…",
    "Helping a hedgehog with a map…",
    "Locating the quietest waterfall…",
    "Making notes on birch bark…",
    "Finding the friendly fireflies…",
    "Checking the fairy timetable…",
    "Following the wandering brook…",
    "Borrowing a leafy umbrella…",
    "Asking a druid about shortcuts…",
    "Looking for the mossy signpost…",
    "Keeping the lantern out of rain…",
    "Tracing a trail of acorn caps…",
    "Waiting for the woodland quorum…",
    "Reading the roots' footnotes…",
    "Counting friendly will-o-wisps…",
    "Giving a mushroom more room…",
    "Checking the tree's mailbox…",
    "Offering the sprite a thimble…",
    "Following the clearer tracks…",
    "Finding a riddle-free bridge…",
    "Listening to the elder fern…",
    "Returning a borrowed pinecone…",
    "Keeping the forest sprites busy…",
    "Consulting the ship's chart…",
    "Counting the spare tentacles…",
    "Finding the least soggy scroll…",
    "Waiting for the tide oracle…",
    "Negotiating with a sea serpent…",
    "Checking the merfolk signposts…",
    "Keeping the compass out of kelp…",
    "Borrowing a pirate's pencil…",
    "Sorting pearls from marbles…",
    "Finding the sunken library…",
    "Calming a dramatic kraken…",
    "Reading the captain's margins…",
    "Untangling the anchor chain…",
    "Checking the lighthouse rhythm…",
    "Following a helpful jellyfish…",
    "Finding the ship's spare wheel…",
    "Giving the parrot a footnote…",
    "Inspecting a treasure-like rock…",
    "Keeping the map above water…",
    "Counting the nautical detours…",
    "Looking for the clockwork key…",
    "Rewinding the brass butterfly…",
    "Adjusting the airship goggles…",
    "Listening to the gearbox goblin…",
    "Finding the less squeaky gear…",
    "Checking the automaton's watch…",
    "Giving the boiler a pep talk…",
    "Sorting the brass doohickeys…",
    "Calibrating the pocket airship…",
    "Waiting for the clockwork owl…",
    "Following the pneumatic map…",
    "Filing a dirigible flight plan…",
    "Inspecting a spring-loaded clue…",
    "Counting the emergency rivets…",
    "Borrowing a tinker's monocle…",
    "Choosing the smaller wrench…",
    "Untangling a clockwork octopus…",
    "Checking the tea-powered engine…",
    "Finding the spare cogwheel…",
    "Keeping the zeppelin on course…",
    "Consulting the star chart…",
    "Counting the escape pods…",
    "Negotiating with a space goblin…",
    "Checking the asteroid detour…",
    "Finding the quietest moon…",
    "Refueling an imaginary rocket…",
    "Teaching a robot to daydream…",
    "Keeping the nebula neatly filed…",
    "Waiting for the orbital kettle…",
    "Reading the alien's footnotes…",
    "Adjusting the telescope scarf…",
    "Checking the moon rover's map…",
    "Following a polite comet…",
    "Untangling the gravity boots…",
    "Finding the spare star key…",
    "Consulting a distant oracle…",
    "Sorting the cosmic souvenirs…",
    "Making room for a small planet…",
    "Keeping the space duck company…",
    "Recounting the constellations…"
  }

  @doc "Returns the number of unique captions in one complete cycle."
  @spec count() :: pos_integer()
  def count do
    tuple_size(@captions)
  end

  @doc "Returns a complete, deterministic tuple of catalog indexes for shuffling."
  @spec order() :: tuple()
  def order do
    0..(count() - 1)
    |> Enum.to_list()
    |> List.to_tuple()
  end

  @doc "Returns the caption at a nonnegative cyclic offset."
  @spec at(non_neg_integer()) :: String.t()
  def at(index) when is_integer(index) and index >= 0 do
    elem(@captions, rem(index, tuple_size(@captions)))
  end
end
